apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-abdosaba
  labels:
    app: backend-abdosaba
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-abdosaba
  template:
    metadata:
      labels:
        app: backend-abdosaba
    spec:
      containers:
      - name: backend-container
        image: abdosaba22/backend:v3
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - backend-abdosaba
            topologyKey: "kubernetes.io/hostname"

