version: '3.8'
services: 
  frontend_service:
    build:
      context: ./frontend
      dockerfile: Dockerfile  
    container_name: frontend
    ports:
      - 8080:80
    networks:
      - frontend_network
    depends_on:
      - backend_service

  backend_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - frontend_network
      - backend_network
    depends_on:
      - database_service
    environment:
      DB_HOST: database_service 
      DB_NAME: db
      DB_USER: abdo       
      DB_PASSWORD: 123456
        
  database_service:
    image: mariadb:latest
    container_name: database
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: db              
      MARIADB_USER: abdo                    
      MARIADB_PASSWORD: 123456        
    volumes:
      - ./databas:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
          
    networks:
      - backend_network
    expose:
      - 3306
        
volumes:
  db_data:

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
